//! Validation against JPL Horizons using SBDB-epoch-anchored reference data.
//!
//! Reference data: validation/horizons_reference_v2.json, generated by
//! `python validation/fetch_horizons_v2.py`. Contains:
//!   - Barycentric ICRF equatorial state vectors at dt=0,30,90,365 days
//!   - Astrometric RA/Dec/rates/range from observers X05, 500, I41
//!
//! Two tests:
//!   1. Propagation: compare ASSIST barycentric equatorial state to Horizons VECTORS.
//!   2. Ephemeris: compare ASSIST-generated astrometric RA/Dec to Horizons OBSERVER.

use std::collections::HashMap;
use std::path::PathBuf;

use rayon::prelude::*;

// ── JSON schema ──────────────────────────────────────────────────────────────

#[derive(serde::Deserialize)]
struct Reference {
    metadata: RefMetadata,
    orbits: Vec<RefOrbit>,
}

#[derive(serde::Deserialize)]
struct RefMetadata {
    #[allow(dead_code)]
    queried_at: String,
    dt_days: Vec<f64>,
    observers: Vec<String>,
}

#[derive(serde::Deserialize)]
struct RefOrbit {
    object_id: String,
    #[allow(dead_code)]
    horizons_des: String,
    sbdb_epoch_jd_tdb: f64,
    non_grav: Option<RefNonGrav>,
    vectors_bary_eq: Vec<RefVector>,
    observer_ephemeris: HashMap<String, Vec<RefObsEpoch>>,
}

#[derive(serde::Deserialize)]
struct RefNonGrav {
    a1: f64,
    a2: f64,
    a3: f64,
    aln: Option<f64>,
    nk: Option<f64>,
    nm: Option<f64>,
    nn: Option<f64>,
    r0: Option<f64>,
}

#[derive(serde::Deserialize)]
struct RefVector {
    jd_tdb: f64,
    x: f64,
    y: f64,
    z: f64,
    vx: f64,
    vy: f64,
    vz: f64,
}

#[derive(serde::Deserialize)]
struct RefObsEpoch {
    jd_tdb: f64,
    ra_deg: f64,
    dec_deg: f64,
    dra_cosdec_arcsec_hr: f64,
    ddec_arcsec_hr: f64,
    delta_au: f64,
    deldot_km_s: f64,
}

// ── Helpers ──────────────────────────────────────────────────────────────────

const AU_M: f64 = 149_597_870_700.0;

fn ephem_paths() -> Option<(PathBuf, PathBuf)> {
    let p = std::env::var("ASSIST_PLANETS_PATH").ok()?;
    let a = std::env::var("ASSIST_ASTEROIDS_PATH").ok()?;
    Some((PathBuf::from(p), PathBuf::from(a)))
}

fn cache_dir() -> PathBuf {
    if let Ok(d) = std::env::var("ASSIST_DATA_DIR") {
        return PathBuf::from(d);
    }
    if let Ok(x) = std::env::var("XDG_CACHE_HOME") {
        return PathBuf::from(x).join("assist-rs");
    }
    let h = std::env::var("HOME").expect("HOME not set");
    PathBuf::from(h).join(".cache").join("assist-rs")
}

fn load_reference() -> Option<Reference> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("validation")
        .join("horizons_reference_v2.json");
    if !p.exists() {
        return None;
    }
    serde_json::from_str(&std::fs::read_to_string(&p).ok()?).ok()
}

/// Resolve an Earth orientation kernel path, preferring the B612 naif-eop-*
/// Python package's env-var override (set by CI) and falling back to the
/// filename inside `ASSIST_DATA_DIR` for local dev.
fn resolve_eop_path(env_var: &str, filenames: &[&str]) -> Option<PathBuf> {
    if let Ok(p) = std::env::var(env_var) {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let dir = cache_dir();
    for name in filenames {
        let p = dir.join(name);
        if p.exists() {
            return Some(p);
        }
    }
    None
}

fn load_earth_orientation() -> Option<assist_rs::earth_orientation::EarthOrientation> {
    // SPICE-idiomatic load order: predict first, historical next, current
    // high-precision last so it wins wherever it has coverage.
    let predict = resolve_eop_path(
        "ASSIST_EOP_PREDICT",
        &[
            "earth_200101_990827_predict.bpc",
            "earth_2025_250826_2125_predict.bpc",
        ],
    );
    let historical = resolve_eop_path(
        "ASSIST_EOP_HISTORICAL",
        &["earth_620120_240827.bpc", "earth_620120_250826.bpc"],
    );
    let current = resolve_eop_path("ASSIST_EOP_HIGH_PREC", &["earth_latest_high_prec.bpc"])?;

    let mut paths: Vec<PathBuf> = Vec::new();
    if let Some(p) = predict {
        paths.push(p);
    }
    if let Some(h) = historical {
        paths.push(h);
    }
    paths.push(current);

    assist_rs::earth_orientation::EarthOrientation::from_paths(&paths).ok()
}

fn jd_to_mjd(jd: f64) -> f64 {
    jd - 2_400_000.5
}

fn mjd_to_assist_time(mjd_tdb: f64, jd_ref: f64) -> f64 {
    (mjd_tdb + 2_400_000.5) - jd_ref
}

/// Convert barycentric equatorial ICRF state → heliocentric ecliptic J2000.
fn bary_eq_to_helio_ecl(
    bary_eq: &[f64; 6],
    ephem: &assist_rs::Ephemeris,
    mjd_tdb: f64,
) -> [f64; 6] {
    let t = mjd_to_assist_time(mjd_tdb, ephem.jd_ref());
    let sun = ephem
        .get_body_state(assist_rs::ffi::ASSIST_BODY_SUN, t)
        .expect("Sun state");
    let helio_eq = [
        bary_eq[0] - sun.x,
        bary_eq[1] - sun.y,
        bary_eq[2] - sun.z,
        bary_eq[3] - sun.vx,
        bary_eq[4] - sun.vy,
        bary_eq[5] - sun.vz,
    ];
    assist_rs::equatorial_to_ecliptic(&helio_eq)
}

/// Convert heliocentric ecliptic J2000 state → barycentric equatorial ICRF.
fn helio_ecl_to_bary_eq(
    helio_ecl: &[f64; 6],
    ephem: &assist_rs::Ephemeris,
    mjd_tdb: f64,
) -> [f64; 6] {
    let t = mjd_to_assist_time(mjd_tdb, ephem.jd_ref());
    let sun = ephem
        .get_body_state(assist_rs::ffi::ASSIST_BODY_SUN, t)
        .expect("Sun state");
    let helio_eq = assist_rs::ecliptic_to_equatorial(helio_ecl);
    [
        helio_eq[0] + sun.x,
        helio_eq[1] + sun.y,
        helio_eq[2] + sun.z,
        helio_eq[3] + sun.vx,
        helio_eq[4] + sun.vy,
        helio_eq[5] + sun.vz,
    ]
}

fn build_orbit(
    ic_bary_eq: &[f64; 6],
    epoch_mjd: f64,
    non_grav: Option<&RefNonGrav>,
    ephem: &assist_rs::Ephemeris,
) -> assist_rs::Orbit {
    let helio_ecl = bary_eq_to_helio_ecl(ic_bary_eq, ephem, epoch_mjd);
    match non_grav {
        Some(ng) => {
            let mut p = assist_rs::NonGravParams::new(ng.a1, ng.a2, ng.a3);
            p.alpha = ng.aln;
            p.nk = ng.nk;
            p.nm = ng.nm;
            p.nn = ng.nn;
            p.r0 = ng.r0;
            assist_rs::Orbit::with_non_grav(helio_ecl, epoch_mjd, p)
        }
        None => assist_rs::Orbit::new(helio_ecl, epoch_mjd),
    }
}

fn angular_separation_rad(ra1: f64, dec1: f64, ra2: f64, dec2: f64) -> f64 {
    let (sin_d1, cos_d1) = dec1.sin_cos();
    let (sin_d2, cos_d2) = dec2.sin_cos();
    let dra = ra1 - ra2;
    let (sin_dra, cos_dra) = dra.sin_cos();
    let num =
        ((cos_d2 * sin_dra).powi(2) + (cos_d1 * sin_d2 - sin_d1 * cos_d2 * cos_dra).powi(2)).sqrt();
    let den = sin_d1 * sin_d2 + cos_d1 * cos_d2 * cos_dra;
    num.atan2(den)
}

// ── Test 1: Propagation (barycentric equatorial vectors) ─────────────────────

#[test]
fn test_propagation_against_horizons() {
    let Some((planets, asteroids)) = ephem_paths() else {
        eprintln!("Skipping: ASSIST_PLANETS_PATH / ASSIST_ASTEROIDS_PATH not set");
        return;
    };
    let Some(reference) = load_reference() else {
        eprintln!("Skipping: validation/horizons_reference_v2.json not found");
        return;
    };
    let ephem =
        assist_rs::Ephemeris::from_paths(&planets, &asteroids).expect("Failed to load ephemeris");

    eprintln!(
        "Propagation test: {} orbits, dt = {:?} days",
        reference.orbits.len(),
        reference.metadata.dt_days
    );

    // 2 Pallas is a massive perturber in sb441-n16; ASSIST perturbs the test
    // particle by its own gravitational field, making comparison meaningless.
    let results: Vec<_> = reference
        .orbits
        .par_iter()
        .filter(|e| !e.object_id.contains("Pallas"))
        .map(|entry| {
            let epoch_mjd = jd_to_mjd(entry.sbdb_epoch_jd_tdb);
            let ic = &entry.vectors_bary_eq[0];
            let ic_arr = [ic.x, ic.y, ic.z, ic.vx, ic.vy, ic.vz];
            let orbit = build_orbit(&ic_arr, epoch_mjd, entry.non_grav.as_ref(), &ephem);

            let target_epochs: Vec<f64> = entry
                .vectors_bary_eq
                .iter()
                .map(|v| jd_to_mjd(v.jd_tdb))
                .collect();

            let propagated = assist_rs::assist_propagate(&ephem, &orbit, &target_epochs, false)
                .unwrap_or_else(|e| panic!("Propagation failed for {}: {e}", entry.object_id));

            let mut rows: Vec<(f64, f64, f64)> = Vec::new(); // (dt, pos_err_m, vel_err_m_s)
            for (prop, href) in propagated.iter().zip(entry.vectors_bary_eq.iter()) {
                let bary_eq = helio_ecl_to_bary_eq(&prop.state, &ephem, jd_to_mjd(href.jd_tdb));
                let dp = [
                    bary_eq[0] - href.x,
                    bary_eq[1] - href.y,
                    bary_eq[2] - href.z,
                ];
                let dv = [
                    bary_eq[3] - href.vx,
                    bary_eq[4] - href.vy,
                    bary_eq[5] - href.vz,
                ];
                let pos_m = (dp[0] * dp[0] + dp[1] * dp[1] + dp[2] * dp[2]).sqrt() * AU_M;
                let vel_ms =
                    (dv[0] * dv[0] + dv[1] * dv[1] + dv[2] * dv[2]).sqrt() * AU_M / 86_400.0;
                let dt = href.jd_tdb - entry.sbdb_epoch_jd_tdb;
                rows.push((dt, pos_m, vel_ms));
            }
            (entry.object_id.clone(), rows)
        })
        .collect();

    // Tolerances per dt bucket (meters)
    // dt=0: pure round-trip, should be < 10 m
    // dt=30: < 100 m (ASSIST vs Horizons integrator differences)
    // dt=90: < 1 km
    // dt=365: < 10 km (long-term integrator divergence)
    let dt_tols_m: &[(f64, f64)] = &[
        (0.0, 10.0),
        (30.0, 500.0),
        (90.0, 5_000.0),
        (365.0, 50_000.0),
    ];

    let mut any_fail = false;
    eprintln!(
        "\n{:<36} {:>8} {:>14} {:>14}",
        "object", "dt", "pos_err_m", "vel_err_m/s"
    );
    for (name, rows) in &results {
        for &(dt, pos_m, vel_ms) in rows {
            let tol = dt_tols_m
                .iter()
                .find(|(d, _)| (*d - dt).abs() < 0.5)
                .map(|(_, t)| *t)
                .unwrap_or(50_000.0);
            let ok = pos_m < tol;
            let flag = if ok { " " } else { "!" };
            eprintln!(
                "{}{:<35} {:>8.0} {:>14.3} {:>14.6}",
                flag, name, dt, pos_m, vel_ms
            );
            if !ok {
                any_fail = true;
            }
        }
    }
    assert!(!any_fail, "Some propagation residuals exceeded tolerance");
}

// ── Test 2: Ephemeris (full validation) ──────────────────────────────────────

/// Per-epoch comparison results.
struct EphemRow {
    dt: f64,
    sep_mas: f64,
    delta_err_m: f64,
    deldot_err_m_s: f64,
    dra_err_mas_hr: f64,
    ddec_err_mas_hr: f64,
    lt_err_us: f64,
}

#[test]
fn test_ephemeris_against_horizons_v2() {
    let Some((planets, asteroids)) = ephem_paths() else {
        eprintln!("Skipping: ASSIST_PLANETS_PATH / ASSIST_ASTEROIDS_PATH not set");
        return;
    };
    let Some(reference) = load_reference() else {
        eprintln!("Skipping: validation/horizons_reference_v2.json not found");
        return;
    };

    // Prefer the B612 mpc-obscodes Python package (CI sets MPC_OBSCODES_PATH),
    // falling back to a cached file in ASSIST_DATA_DIR for local dev.
    let obscodes = std::env::var("MPC_OBSCODES_PATH")
        .map(PathBuf::from)
        .ok()
        .filter(|p| p.exists())
        .unwrap_or_else(|| cache_dir().join("obscodes_extended.json"));
    if !obscodes.exists() {
        eprintln!("Skipping: {} not found", obscodes.display());
        return;
    }
    let obs_table =
        assist_rs::ObservatoryTable::from_json(&obscodes).expect("Failed to load obs table");
    let obs_table = match load_earth_orientation() {
        Some(eo) => {
            eprintln!("Earth orientation loaded ({} segments)", eo.segment_count());
            obs_table.with_earth_orientation(eo)
        }
        None => {
            eprintln!("WARNING: no EO kernel; using GMST fallback");
            obs_table
        }
    };

    let ephem =
        assist_rs::Ephemeris::from_paths(&planets, &asteroids).expect("Failed to load ephemeris");

    let c_au_day = ephem.c_au_per_day();
    let rad_to_mas = 180.0 / std::f64::consts::PI * 3600.0 * 1000.0;
    // rad/day → arcsec/hr
    let rad_day_to_arcsec_hr = 206_264.806_247_096_36 / 24.0;
    // AU → m
    let au_m = 149_597_870_700.0;
    // AU/day → km/s
    let au_day_to_km_s = au_m / (86_400.0 * 1000.0);
    // days → microseconds
    let day_to_us = 86_400.0e6;

    eprintln!(
        "Ephemeris test: {} orbits, observers {:?}",
        reference.orbits.len(),
        reference.metadata.observers
    );

    // Flatten to (orbit, observer_code) pairs.
    let jobs: Vec<(&RefOrbit, &String)> = reference
        .orbits
        .iter()
        .filter(|o| !o.object_id.contains("Pallas"))
        .flat_map(|o| reference.metadata.observers.iter().map(move |c| (o, c)))
        .collect();

    let results: Vec<(String, String, Vec<EphemRow>)> = jobs
        .par_iter()
        .map(|(entry, obs_code)| {
            let epoch_mjd = jd_to_mjd(entry.sbdb_epoch_jd_tdb);
            let ic = &entry.vectors_bary_eq[0];
            let ic_arr = [ic.x, ic.y, ic.z, ic.vx, ic.vy, ic.vz];
            let orbit = build_orbit(&ic_arr, epoch_mjd, entry.non_grav.as_ref(), &ephem);

            let horizons_obs = entry
                .observer_ephemeris
                .get(*obs_code)
                .expect("missing observer");

            let observers: Vec<assist_rs::Observer> = horizons_obs
                .iter()
                .map(|o| {
                    assist_rs::Observer::new(
                        assist_rs::Origin::Observatory((*obs_code).clone()),
                        jd_to_mjd(o.jd_tdb),
                    )
                })
                .collect();

            let predicted = assist_rs::assist_generate_ephemeris(
                &ephem,
                &orbit,
                &observers,
                Some(&obs_table),
                1,
            )
            .unwrap_or_else(|e| {
                panic!(
                    "Ephemeris failed for {} @ {}: {e}",
                    entry.object_id, obs_code
                )
            });

            let mut rows = Vec::new();
            for (pr, href) in predicted.iter().zip(horizons_obs.iter()) {
                let dt = href.jd_tdb - entry.sbdb_epoch_jd_tdb;

                // Angular position (RA/Dec)
                let ra_rust = pr.spherical[1];
                let dec_rust = pr.spherical[2];
                let ra_hor = href.ra_deg.to_radians();
                let dec_hor = href.dec_deg.to_radians();
                let sep_mas =
                    angular_separation_rad(ra_rust, dec_rust, ra_hor, dec_hor) * rad_to_mas;

                // Range (delta)
                let delta_rust_au = pr.spherical[0];
                let delta_err_m = (delta_rust_au - href.delta_au).abs() * au_m;

                // Range rate (deldot)
                let deldot_rust_km_s = pr.spherical[3] * au_day_to_km_s;
                let deldot_err_m_s = (deldot_rust_km_s - href.deldot_km_s).abs() * 1000.0;

                // RA rate: our dRA (rad/day) × cos(dec) → arcsec/hr
                let dra_cosdec_rust = pr.spherical[4] * dec_rust.cos() * rad_day_to_arcsec_hr;
                let dra_err_mas_hr = (dra_cosdec_rust - href.dra_cosdec_arcsec_hr).abs() * 1000.0;

                // Dec rate: our dDec (rad/day) → arcsec/hr
                let ddec_rust = pr.spherical[5] * rad_day_to_arcsec_hr;
                let ddec_err_mas_hr = (ddec_rust - href.ddec_arcsec_hr).abs() * 1000.0;

                // Light time: barycentric range / c vs Horizons range / c
                let lt_ours_days = delta_rust_au / c_au_day;
                let lt_horizons_days = href.delta_au / c_au_day;
                let lt_err_us = (lt_ours_days - lt_horizons_days).abs() * day_to_us;

                rows.push(EphemRow {
                    dt,
                    sep_mas,
                    delta_err_m,
                    deldot_err_m_s,
                    dra_err_mas_hr,
                    ddec_err_mas_hr,
                    lt_err_us,
                });
            }
            (entry.object_id.clone(), (*obs_code).clone(), rows)
        })
        .collect();

    // Tolerances:
    // - Angular position: < 1 mas (sub-mas validated)
    // - Range: < 150 m (DE440 vs DE441 + propagation divergence at 365d)
    // - Range rate: < 0.01 m/s
    // - Angular rates: < 1000 mas/hr. Horizons QUANTITIES='3' rates are
    //   derivatives of *apparent* positions (including stellar aberration),
    //   while our rates are *astrometric* (no aberration). The rate of change
    //   of the aberration correction scales with Earth's acceleration and the
    //   object's angular speed: ~5 mas/hr for slow TNOs, ~660 mas/hr for
    //   fast close NEAs. Our rates match FD of Horizons' astrometric
    //   positions (QUANTITIES='1') to < 1 mas/hr.
    // - Light time: < 1.0 μs (derived from range tolerance: 150m / c ≈ 0.5 μs)
    let tol_sep_mas = 1.0;
    let tol_delta_m = 150.0;
    let tol_deldot_m_s = 0.01;
    let tol_dra_mas_hr = 1000.0;
    let tol_ddec_mas_hr = 1000.0;
    let tol_lt_us = 1.0;

    let mut any_fail = false;
    eprintln!(
        "\n{:<36} {:<4} {:>4} {:>10} {:>10} {:>10} {:>10} {:>10} {:>10}",
        "object",
        "obs",
        "dt",
        "sep_mas",
        "delta_m",
        "deldot_m/s",
        "dRA_mas/h",
        "dDec_mas/h",
        "lt_us"
    );
    for (name, obs, rows) in &results {
        for row in rows {
            let ok = row.sep_mas < tol_sep_mas
                && row.delta_err_m < tol_delta_m
                && row.deldot_err_m_s < tol_deldot_m_s
                && row.dra_err_mas_hr < tol_dra_mas_hr
                && row.ddec_err_mas_hr < tol_ddec_mas_hr
                && row.lt_err_us < tol_lt_us;
            let flag = if ok { " " } else { "!" };
            eprintln!(
                "{}{:<35} {:<4} {:>4.0} {:>10.4} {:>10.3} {:>10.4} {:>10.2} {:>10.2} {:>10.4}",
                flag,
                name,
                obs,
                row.dt,
                row.sep_mas,
                row.delta_err_m,
                row.deldot_err_m_s,
                row.dra_err_mas_hr,
                row.ddec_err_mas_hr,
                row.lt_err_us,
            );
            if !ok {
                any_fail = true;
            }
        }
    }

    assert!(!any_fail, "Some ephemeris residuals exceeded tolerances");
}
